---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erick.
--- DateTime: 24/08/2022 16:34
---

-- ============================================================================
-- 💖 HOMENAGEM E AGRADECIMENTO AO CRIADOR ORIGINAL
-- Este arquivo foi adaptado e integrado como parte do LKS SuperMod Patch.
-- Agradecemos imensamente a Erick (4422) pelo mod original "Fridges Off!"
-- (ID Workshop: 2853974107) por sua fantástica contribuição para a comunidade!
-- ============================================================================

-- ============================================================================
-- ARQUIVO: fridgesoff_client.lua
print("[LKS PATCH - fridgesoff_client.lua] Carregando Lógica Cliente do Fridges Off!...")
-- EXTENSÃO: LKS SuperMod Patch (Fagocitado nativamente)
-- CRÉDITOS DO MOD ORIGINAL: Fridges Off! (ID Workshop: 2853974107) por 4422 (Erick)
-- OBJETIVO: Gerenciamento cliente para ligar/desligar geladeiras e congeladores.
-- ============================================================================
-- FUNCIONAMENTO DO CLIENTE:
-- 1. Cria a ação temporizada (Timed Action) 'ISToggleFridgesFreezers' para o
--    personagem interagir com a geladeira/freezer no mundo.
-- 2. Insere opções de menu de contexto ("Ligar" / "Desligar") nos aparelhos.
-- 3. Escuta eventos do servidor para sincronizar graficamente os tipos de
--    contêineres no inventário local quando religados ou desligados.
-- ============================================================================

---@param text String
local function customPrint(text)
    print("fridgesoff_client.lua: " .. text)
end

-- ============================================================================
-- ⏳ AÇÃO TEMPORIZADA DE INTERAÇÃO (TIMED ACTION)
-- Define a caminhada física e a face do personagem em direção ao objeto do mundo.
-- ============================================================================

---@class ISToggleFridgesFreezers : ISBaseTimedAction
ISToggleFridgesFreezers = ISBaseTimedAction:derive("ISToggleFridgesFreezers");

function ISToggleFridgesFreezers:isValid()
    return true
end

function ISToggleFridgesFreezers:update()
end

function ISToggleFridgesFreezers:start()
    self.character:faceThisObject(self.object)
end

function ISToggleFridgesFreezers:stop()
    ISBaseTimedAction.stop(self)
end

function ISToggleFridgesFreezers:perform()

    if self.state == 0 then
        sendClientCommand("fridges-off", "off", {x = self.object:getX(),y = self.object:getY(),z = self.object:getZ()});
    else
        sendClientCommand("fridges-off", "on", {x = self.object:getX(),y = self.object:getY(),z = self.object:getZ()});
    end

    -- needed to remove from queue / start next.
    ISBaseTimedAction.perform(self)
end

function ISToggleFridgesFreezers:new(objPlayer, state, obj)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    o.character = objPlayer
    o.stopOnWalk = false
    o.stopOnRun = false
    o.maxTime = 0
    -- custom fields
    o.object = obj
    o.state = state
    return o
end

-- ============================================================================
-- 🖱️ MENU DE CONTEXTO DO MUNDO (WORLD OBJECT CONTEXT MENU)
-- Insere as opções de menu de tomada baseadas no tipo atual do contêiner do item.
-- ============================================================================

---@param player IsoPlayer
---@param context KahluaTable
---@param worldObjects KahluaTable
---@param _ Boolean
local function customizedContextMenu(player, context, worldObjects, _)

    local objectPlayer = getSpecificPlayer(player)

    if objectPlayer:isAsleep() then
        return
    end

    ---@param objPlayer IsoPlayer
    ---@param state Integer
    ---@param o IsoObject
    local changeFridgeFreezerState = function(_,objPlayer,state,o)
        if luautils.walkAdj(objPlayer, o:getSquare()) then
            ISTimedActionQueue.add(ISToggleFridgesFreezers:new(objPlayer, state, o))
        end
    end

    ---@type IsoObject
    local actualObject = worldObjects[1]

    if actualObject then
        local containerCount = actualObject:getContainerCount()
        if containerCount > 0 then
            local containerType = actualObject:getContainer():getType()
            if containerType == "fridge" or containerType == "freezer" then
                local optionOff = context:addOptionOnTop(getText("ContextMenu_TurnOff") or "Desligar", worldObjects, changeFridgeFreezerState, objectPlayer, 0, actualObject)
                optionOff.iconTexture = getTexture("media/ui/LKS_Pwr_Off.png")
            end
            if containerType == "geladeira_desligada" or containerType == "congelador_desligado" then
                local optionOn = context:addOptionOnTop(getText("ContextMenu_TurnOn") or "Ligar", worldObjects, changeFridgeFreezerState, objectPlayer, 1, actualObject)
                optionOn.iconTexture = getTexture("media/ui/LKS_Pwr_On.png")
            end
        end
    end

end

-- ============================================================================
-- 🎨 REGISTRO DE TEXTURAS DE CONTAINER DESLIGADO
-- Carrega os ícones customizados de tomada nas abas laterais do inventário (Loot).
-- ============================================================================
local function loadNewIcons()

    ---@type Texture
    local textureFridgeOff = getTexture("media/ui/Container_FridgeOff.png")

    ---@type Texture
    local textureFreezerOff = getTexture("media/ui/Container_FreezerOff.png")

    ContainerButtonIcons.geladeira_desligada = textureFridgeOff
    ContainerButtonIcons.congelador_desligado = textureFreezerOff

end

-- ============================================================================
-- 📡 EVENTO DE SINCRONIZAÇÃO DO CLIENTE (SERVER COMMAND REACTION)
-- Sincroniza localmente o estado visual e elétrico do aparelho no cliente.
-- ============================================================================
local function onServerCommand(module,command,args)

    if module == "fridges-off" then

        if command == "sync" then

            ---as suggested by @TheLeo, sometimes you can get a null pointer from getGridSquare
            ---this shouldn't happen, because this part is just to replicate a server state
            ---so if you get a null pointer here, it's probably a desync
            ---I'm adding @TheLeo's suggestion because it's good to have checks like this
            ---but I will add a DebugLog (the server has the real version of the game, so it's good to know if something is out of sync or if there are problems loading a chunk/cell correctly)
            local gridSquare = getWorld():getCell():getGridSquare(args.x,args.y,args.z)

            if gridSquare == nil then
                customPrint(getText("IGUI_PB_Debug_DesyncSquare") or "can't find this square, probably a desync")
                return
            end

            local objects = getWorld():getCell():getGridSquare(args.x,args.y,args.z):getObjects()

            if objects ~= nil then

                ---@type IsoObject
                local object

                for i=0,objects:size()-1,1 do
                    if objects:get(i):getContainerCount() > 0 then
                        if objects:get(i):getContainerByEitherType("fridge","freezer") or objects:get(i):getContainerByEitherType("geladeira_desligada","congelador_desligado") then
                            object = objects:get(i)
                            break
                        end
                    end
                end

                if object ~= nil then

                    if args.fridge == "on" then
                        if object:getContainerByType("geladeira_desligada") ~= nil then
                            object:getContainerByType("geladeira_desligada"):setType("fridge")
                        end
                    else
                        if args.fridge == "off" then
                            if object:getContainerByType("fridge") ~= nil then
                                object:getContainerByType("fridge"):setType("geladeira_desligada")
                            end
                        end
                    end

                    if args.freezer == "on" then
                        if object:getContainerByType("congelador_desligado") ~= nil then
                            object:getContainerByType("congelador_desligado"):setType("freezer")
                        end
                    else
                        if args.freezer == "off" then
                            if object:getContainerByType("freezer") ~= nil then
                                object:getContainerByType("freezer"):setType("congelador_desligado")
                            end
                        end
                    end

                    -- Força a atualização do gerador no mapa
                    IsoGenerator.updateGenerator(object:getSquare())

                    -- Recalcula se o objeto tem eletricidade após a transição
                    object:checkHaveElectricity()

                    local playerData = getPlayerData(getPlayer():getPlayerNum())
                    if playerData ~= nil then
                        playerData.playerInventory:refreshBackpacks()
                        playerData.lootInventory:refreshBackpacks()
                    end

                end
            else
                customPrint(getText("IGUI_PB_Debug_DesyncObject") or "can't find any object on this square, probably a desync")
            end
        end
    end
end

Events.OnGameBoot.Add(loadNewIcons)
Events.OnPreFillWorldObjectContextMenu.Add(customizedContextMenu)
Events.OnServerCommand.Add(onServerCommand)

print("[LKS PATCH - fridgesoff_client.lua] Carregado com sucesso!")