---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erick.
--- DateTime: 24/08/2022 16:34
---

-- ============================================================================
-- 💖 HOMENAGEM E AGRADECIMENTO AO CRIADOR ORIGINAL
-- Este arquivo foi adaptado e integrado como parte do LKS SuperMod Patch.
-- Agradecemos imensamente a Erick (4422) pelo mod original "Fridges Off!"
-- (ID Workshop: 2853974107) por sua fantástica contribuição para a comunidade!
-- ============================================================================

-- ============================================================================
-- ARQUIVO: fridgesoff_server.lua
print("[LKS PATCH - fridgesoff_server.lua] Carregando Lógica Servidor do Fridges Off!...")
-- EXTENSÃO: LKS SuperMod Patch (Fagocitado nativamente)
-- CRÉDITOS DO MOD ORIGINAL: Fridges Off! (ID Workshop: 2853974107) por 4422 (Erick)
-- OBJETIVO: Gerenciamento no lado do servidor para ligar/desligar geladeiras.
-- ============================================================================
-- FUNCIONAMENTO DO SERVIDOR:
-- 1. Recebe comandos enviados pelo cliente ("on" / "off").
-- 2. Altera o tipo dos contêineres ("fridge"/"freezer" <-> "geladeira_desligada"/"congelador_desligado").
-- 3. Força a atualização do consumo de energia nos geradores ao redor.
-- 4. Reenvia as informações aos clientes para sincronização visual.
-- ============================================================================

if isClient() then return end

---@param text String
local function customPrint(text)
    print("fridgesoff_server.lua: " .. text)
end

-- ============================================================================
-- ⚡ ATUALIZAÇÃO DOS GERADORES DA CONCENTRAÇÃO
-- Varre uma área 40x40 nos andares próximos para forçar os geradores a recalcularem
-- o consumo elétrico quando uma geladeira é ligada ou desligada.
-- ============================================================================

---@param cX Integer
---@param cY Integer
---@param cZ Integer
function updateGenerators(cX, cY, cZ)
    local minX = cX - 20
    local maxX = cX + 20
    local minY = cY - 20
    local maxY = cY + 20
    local tempCZ = cZ
    local minZ = Math.max(0, tempCZ - 3)
    local maxZ = Math.min(8, tempCZ + 3)
    for gZ=minZ,maxZ-1,1 do
        for gX=minX,maxX,1 do
            for gY=minY,maxY,1 do
                local utility = IsoUtils.DistanceToSquared(gX+.5,gY+.5,cX+.5,cY+.5)
                if utility <= 400.0 then
                    local actualCell = getWorld():getCell()
                    local actualSquare = actualCell:getGridSquare(gX,gY,gZ)
                    if actualSquare ~= nil then
                        for i=0,actualSquare:getObjects():size()-1,1 do
                            ---@type IsoObject
                            local actualObject = actualSquare:getObjects():get(i)
                            if actualObject ~= nil and instanceof(actualObject,"IsoGenerator") then
                                ---@type IsoGenerator
                                actualObject:setSurroundingElectricity()
                            end
                        end
                    end
                end
            end
        end
    end
end

-- ============================================================================
-- 📡 COMANDO DE REDE RECEBIDO DO CLIENTE
-- Processa a solicitação do jogador e altera o tipo do contêiner correspondente.
-- ============================================================================

---@param module String
---@param command String
---@param player IsoPlayer
---@param args KahluaTable
local function onClientCommand(module,command,player,args)

    if module == "fridges-off" then

        local gridSquare = getWorld():getCell():getGridSquare(args.x,args.y,args.z)

        if gridSquare == nil then
            customPrint(getText("IGUI_PB_Debug_DesyncSquare") or "Não foi possível encontrar este quadrado, provável dessincronização")
            return
        end

        local objects = getWorld():getCell():getGridSquare(args.x,args.y,args.z):getObjects()

        if objects ~= nil then

            ---@type IsoObject
            local object

            for i=0,objects:size()-1,1 do
                if objects:get(i):getContainerCount() > 0 then
                    if objects:get(i):getContainerByEitherType("fridge","freezer") or objects:get(i):getContainerByEitherType("geladeira_desligada","congelador_desligado") then
                        object = objects:get(i)
                        break
                    end
                end
            end

            if object ~= nil then

                if command == "on" then

                    if object:getContainerByType("geladeira_desligada") ~= nil then
                        object:getContainerByType("geladeira_desligada"):setType("fridge")
                    end

                    if object:getContainerByType("congelador_desligado") ~= nil then
                        object:getContainerByType("congelador_desligado"):setType("freezer")
                    end

                end

                if command == "off" then

                    if object:getContainerByType("fridge") ~= nil then
                        object:getContainerByType("fridge"):setType("geladeira_desligada")
                    end

                    if object:getContainerByType("freezer") ~= nil then
                        object:getContainerByType("freezer"):setType("congelador_desligado")
                    end

                end

                updateGenerators(object:getContainer():getSourceGrid():getX(),object:getContainer():getSourceGrid():getY(),object:getContainer():getSourceGrid():getZ())

                object:checkHaveElectricity()

                local fridge
                local freezer

                if object:getContainerByType("fridge") ~= nil then
                    fridge = "on"
                else
                    if object:getContainerByType("geladeira_desligada") ~= nil then
                        fridge = "off"
                    else
                        fridge = "empty"
                    end
                end

                if object:getContainerByType("freezer") ~= nil then
                    freezer = "on"
                else
                    if object:getContainerByType("congelador_desligado") ~= nil then
                        freezer = "off"
                    else
                        freezer = "empty"
                    end
                end

                if isServer() then
                    sendServerCommand("fridges-off","sync",{x=args.x,y=args.y,z=args.z,fridge=fridge,freezer=freezer})
                end

                if not isServer() and not isClient() then
                    local playerData = getPlayerData(getPlayer():getPlayerNum())
                    if playerData ~= nil then
                        playerData.playerInventory:refreshBackpacks()
                        playerData.lootInventory:refreshBackpacks()
                    end
                end

            end
        else
            customPrint(getText("IGUI_PB_Debug_DesyncObject") or "Não foi possível encontrar nenhum objeto neste quadrado, provável dessincronização")
        end
    end
end

Events.OnClientCommand.Add(onClientCommand)

print("[LKS PATCH - fridgesoff_server.lua] Carregado com sucesso!")